# Generated by Django 6.0 on 2025-12-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0004_leaverequest_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timing',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='days_requested',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('planned', 'Planned'), ('unplanned', 'Unplanned')], max_length=20),
        ),
    ]
