# Generated by Django 6.0 on 2025-12-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_remove_attendance_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='days_requested',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
