# Generated by Django 6.0 on 2026-01-03 11:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authe', '0011_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_location',
            field=models.CharField(blank=True, help_text='Check-in location (lat,lng)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_location',
            field=models.CharField(blank=True, help_text='Check-out location (lat,lng)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='distance_from_office',
            field=models.FloatField(blank=True, help_text='Distance in meters', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_location_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attendance_radius',
            field=models.FloatField(default=500.0, help_text='Allowed attendance radius in meters'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_location',
            field=models.CharField(blank=True, help_text='Office location (lat,lng)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('auto_not_marked', 'Auto Not Marked')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dccb',
            field=models.CharField(blank=True, choices=[('AHMEDABAD', 'AHMEDABAD'), ('BANASKANTHA', 'BANASKANTHA'), ('BARODA', 'BARODA'), ('MAHESANA', 'MAHESANA'), ('SABARKANTHA', 'SABARKANTHA'), ('BHARUCH', 'BHARUCH'), ('KHEDA', 'KHEDA'), ('PANCHMAHAL', 'PANCHMAHAL'), ('SURENDRANAGAR', 'SURENDRANAGAR'), ('JAMNAGAR', 'JAMNAGAR'), ('JUNAGADH', 'JUNAGADH'), ('KODINAR', 'KODINAR'), ('KUTCH', 'KUTCH'), ('VALSAD', 'VALSAD'), ('AMRELI', 'AMRELI'), ('BHAVNAGAR', 'BHAVNAGAR'), ('RAJKOT', 'RAJKOT'), ('SURAT', 'SURAT')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('MT', 'MT'), ('DC', 'DC'), ('Support', 'Support'), ('Manager', 'Manager'), ('HR', 'HR'), ('Delivery Head', 'Delivery Head')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^(MGJ[0-9]{5}|MP[0-9]{4})$', 'Invalid Employee ID format')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('field_officer', 'Field Officer'), ('admin', 'Admin')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='dccb',
            field=models.CharField(blank=True, choices=[('AHMEDABAD', 'AHMEDABAD'), ('BANASKANTHA', 'BANASKANTHA'), ('BARODA', 'BARODA'), ('MAHESANA', 'MAHESANA'), ('SABARKANTHA', 'SABARKANTHA'), ('BHARUCH', 'BHARUCH'), ('KHEDA', 'KHEDA'), ('PANCHMAHAL', 'PANCHMAHAL'), ('SURENDRANAGAR', 'SURENDRANAGAR'), ('JAMNAGAR', 'JAMNAGAR'), ('JUNAGADH', 'JUNAGADH'), ('KODINAR', 'KODINAR'), ('KUTCH', 'KUTCH'), ('VALSAD', 'VALSAD'), ('AMRELI', 'AMRELI'), ('BHAVNAGAR', 'BHAVNAGAR'), ('RAJKOT', 'RAJKOT'), ('SURAT', 'SURAT')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_national',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('planned', 'Planned'), ('unplanned', 'Unplanned')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'user'], name='authe_atten_date_12bb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'status'], name='authe_atten_user_id_62d4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='authe_atten_date_d0c4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['marked_at'], name='authe_atten_marked__06d25b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['employee_id'], name='authe_custo_employe_a1089f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='authe_custo_role_8db104_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['dccb', 'designation'], name='authe_custo_dccb_e73cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='authe_holid_date_75f898_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['dccb', 'date'], name='authe_holid_dccb_c36732_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', 'status'], name='authe_leave_user_id_e1bf61_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'applied_at'], name='authe_leave_status_de7da2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='authe_leave_start_d_87cb3c_idx'),
        ),
    ]
