# Generated by Django 6.0 on 2026-01-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0014_add_location_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Latitude', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Longitude', null=True),
        ),
    ]
