# Generated by Django 6.0 on 2025-12-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0007_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('name', 'date')},
            },
        ),
    ]
