# Generated by Django 6.0 on 2026-01-02 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0008_customuser_registration_at_customuser_status_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
