# Generated by Django 6.0 on 2026-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0009_delete_holiday_remove_customuser_registration_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
