# Generated by Django 6.0 on 2026-01-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0013_customuser_is_demo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
    ]
