# Generated by Django 6.0 on 2026-01-08 08:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0016_remove_attendance_check_in_location_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='holiday',
            name='authe_holid_date_75f898_idx',
        ),
        migrations.RemoveIndex(
            model_name='holiday',
            name='authe_holid_dccb_c36732_idx',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='authe_atten_date_12bb5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='authe_atten_user_id_62d4e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='authe_atten_date_d0c4d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='authe_atten_marked__06d25b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='authe_custo_employe_a1089f_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='authe_custo_role_8db104_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='authe_custo_dccb_e73cb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='authe_leave_user_id_e1bf61_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='authe_leave_status_de7da2_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='authe_leave_start_d_87cb3c_idx',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='distance_from_office',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_location_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('auto_not_marked', 'Auto Not Marked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dccb',
            field=models.CharField(blank=True, choices=[('AHMEDABAD', 'AHMEDABAD'), ('BANASKANTHA', 'BANASKANTHA'), ('BARODA', 'BARODA'), ('MAHESANA', 'MAHESANA'), ('SABARKANTHA', 'SABARKANTHA'), ('BHARUCH', 'BHARUCH'), ('KHEDA', 'KHEDA'), ('PANCHMAHAL', 'PANCHMAHAL'), ('SURENDRANAGAR', 'SURENDRANAGAR'), ('JAMNAGAR', 'JAMNAGAR'), ('JUNAGADH', 'JUNAGADH'), ('KODINAR', 'KODINAR'), ('KUTCH', 'KUTCH'), ('VALSAD', 'VALSAD'), ('AMRELI', 'AMRELI'), ('BHAVNAGAR', 'BHAVNAGAR'), ('RAJKOT', 'RAJKOT'), ('SURAT', 'SURAT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('MT', 'MT'), ('DC', 'DC'), ('Support', 'Support'), ('Manager', 'Manager'), ('HR', 'HR'), ('Delivery Head', 'Delivery Head')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^(MGJ[0-9]{5}|MP[0-9]{4})$', 'Invalid Employee ID format')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('field_officer', 'Field Officer'), ('admin', 'Admin')], max_length=15),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('planned', 'Planned'), ('unplanned', 'Unplanned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='attendance_radius',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_demo_user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='office_latitude',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='office_longitude',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='admin_remarks',
        ),
    ]
