# Generated by Django 6.0 on 2026-01-09 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0018_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='confirmation_source',
            field=models.CharField(choices=[('DC', 'DC'), ('ADMIN', 'Admin')], default='DC', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='confirmed_by_dc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='dc_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_confirmed_by_dc',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DC_CONFIRMATION', 'DC Confirmation'), ('ADMIN_OVERRIDE', 'Admin Override'), ('BULK_UPDATE', 'Bulk Update')], max_length=20)),
                ('affected_employee_count', models.IntegerField()),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('dc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
