# Generated by Django 6.0 on 2026-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0012_alter_customuser_options_remove_attendance_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_demo_user',
            field=models.BooleanField(default=False, help_text='Protected demo user - cannot be deleted'),
        ),
    ]
