# Generated by Django 6.0 on 2026-01-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0023_attendance_is_leave_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
