# Generated by Django 6.0 on 2026-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
