# Generated by Django 6.0 on 2025-12-27 16:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^(MGJ-\\d{5}|MP\\d{4})$', 'Invalid Employee ID format')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be 10 digits')])),
                ('role', models.CharField(choices=[('FIELD', 'Field Staff'), ('ADMIN', 'Admin User')], max_length=10)),
                ('designation', models.CharField(choices=[('MT', 'MT'), ('DC', 'DC'), ('Support', 'Support'), ('Manager', 'Manager'), ('HR', 'HR'), ('Delivery Manager', 'Delivery Manager')], max_length=20)),
                ('dccb', models.CharField(blank=True, choices=[('AHMEDABAD', 'AHMEDABAD'), ('BANASKANTHA', 'BANASKANTHA'), ('BARODA', 'BARODA'), ('MAHESANA', 'MAHESANA'), ('SABARKANTHA', 'SABARKANTHA'), ('BHARUCH', 'BHARUCH'), ('KHEDA', 'KHEDA'), ('PANCHMAHAL', 'PANCHMAHAL'), ('SURENDRANAGAR', 'SURENDRANAGAR'), ('JAMNAGAR', 'JAMNAGAR'), ('JUNAGADH', 'JUNAGADH'), ('KODINAR', 'KODINAR'), ('KUTCH', 'KUTCH'), ('VALSAD', 'VALSAD'), ('AMRELI', 'AMRELI'), ('BHAVNAGAR', 'BHAVNAGAR'), ('RAJKOT', 'RAJKOT'), ('SURAT', 'SURAT')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reporting_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
