# Generated by Django 6.0 on 2025-12-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_alter_customuser_reporting_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
    ]
