# Generated by Django 6.0 on 2026-01-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0022_attendance_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_leave_day',
            field=models.BooleanField(default=False),
        ),
    ]
