# Generated by Django 6.0 on 2026-01-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0010_leaverequest_admin_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dccb', models.CharField(blank=True, choices=[('AHMEDABAD', 'AHMEDABAD'), ('BANASKANTHA', 'BANASKANTHA'), ('BARODA', 'BARODA'), ('MAHESANA', 'MAHESANA'), ('SABARKANTHA', 'SABARKANTHA'), ('BHARUCH', 'BHARUCH'), ('KHEDA', 'KHEDA'), ('PANCHMAHAL', 'PANCHMAHAL'), ('SURENDRANAGAR', 'SURENDRANAGAR'), ('JAMNAGAR', 'JAMNAGAR'), ('JUNAGADH', 'JUNAGADH'), ('KODINAR', 'KODINAR'), ('KUTCH', 'KUTCH'), ('VALSAD', 'VALSAD'), ('AMRELI', 'AMRELI'), ('BHAVNAGAR', 'BHAVNAGAR'), ('RAJKOT', 'RAJKOT'), ('SURAT', 'SURAT')], max_length=20, null=True)),
                ('is_national', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
