# Generated by Django 6.0 on 2026-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0015_attendance_latitude_attendance_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='office_location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_latitude',
            field=models.FloatField(blank=True, help_text='Office latitude', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_longitude',
            field=models.FloatField(blank=True, help_text='Office longitude', null=True),
        ),
    ]
