# Generated by Django 6.0 on 2026-01-21 08:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0019_attendance_confirmation_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('target_table', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('er_id', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{17}$')])),
                ('distance_km', models.IntegerField()),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_approve_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_approve_travel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('field_officer', 'Field Officer'), ('dc', 'DC'), ('mt', 'MT'), ('support', 'Support'), ('associate', 'Associate'), ('admin', 'Admin'), ('hr', 'HR'), ('manager', 'Manager'), ('delivery_head', 'Delivery Head'), ('super_admin', 'Super Admin')], max_length=15),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_travels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['timestamp'], name='system_audi_timesta_8f843c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['actor', 'action_type'], name='system_audi_actor_i_866475_idx'),
        ),
    ]
