# Generated by Django 6.0 on 2026-01-21 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0021_auto_20260121_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='task',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('half_day_late', 'Half Day Late')], default='on_time', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='travel_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='travel_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='travel_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='workplace',
            field=models.CharField(blank=True, choices=[('DCCB', 'DCCB'), ('PACS', 'PACS'), ('WFH', 'WFH'), ('DR office', 'DR office'), ('DDM office', 'DDM office'), ('Training Centre', 'Training Centre'), ('Cluster', 'Cluster'), ('APMC', 'APMC'), ('Branch', 'Branch'), ('Vendor Office', 'Vendor Office')], default='DCCB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='multiple_dccb',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('SPMU', 'SPMU'), ('Central Tech Support', 'Central Tech Support'), ('CCR', 'CCR'), ('Field Support', 'Field Support'), ('IT Admin', 'IT Admin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('MT', 'MT'), ('DC', 'DC'), ('Support', 'Support'), ('Associate', 'Associate'), ('Manager', 'Manager'), ('HR', 'HR'), ('Delivery Head', 'Delivery Head')], max_length=20),
        ),
    ]
