# Generated by Django 6.0 on 2026-01-22 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0024_leaverequest_admin_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='days_count',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='duration',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=10),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='request_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='er_id',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{17}$', 'ER ID must be 17 characters')]),
        ),
    ]
